# Generated by Django 5.2.5 on 2025-08-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maketimeitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maketimeitem',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='maketimeitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='maketimeitem',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
