# Generated by Django 5.2.5 on 2025-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_maketimeitem_contact_email_maketimeitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_time_end',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_time_start',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_commitment',
            field=models.IntegerField(default=0, help_text='Hours per week'),
        ),
    ]
